from __future__ import annotations


STATUS_PASS = "pass"
STATUS_WARN = "warn"
STATUS_WARNING = "warning"
STATUS_FAIL = "fail"

SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_ERROR = "error"

EXIT_PASS = 0
EXIT_FAIL = 1
EXIT_CRASH = 2

VALIDATE_SEVERITY_STATUS = {
    SEVERITY_INFO: STATUS_PASS,
    SEVERITY_WARNING: STATUS_WARN,
    SEVERITY_ERROR: STATUS_FAIL,
}

INSPECT_STATUS_ORDER = {
    STATUS_PASS: 0,
    SEVERITY_INFO: 0,
    STATUS_WARNING: 1,
    STATUS_FAIL: 2,
}

VALIDATE_EXIT_STATUS = {
    STATUS_PASS: EXIT_PASS,
    STATUS_WARN: EXIT_PASS,
    STATUS_FAIL: EXIT_FAIL,
}

